name: sample_carousels_app
description: "The Ultimate Carousel App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          style: normal
          weight: 700